# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_zoo.ipynb (unless otherwise specified).

__all__ = ['G0_ISOLATED_VERTEX', 'G0_TWO_ISOLATED_VERTICES', 'G0_TWO_IDENTIFIED_VERTICES', 'G1_ISOLATED_DART',
           'G1_0101', 'G1_0110', 'G1_1001', 'G1_1010', 'G1_LOOP_1', 'G2_SQUARE_BOUNDED', 'G2_SQUARE_BOUNDED_1',
           'G2_SQUARE_UNBOUNDED', 'G2_ANNULUS_1', 'G2_MOEBIUS_1', 'G2_TORUS_1', 'G2_TWO_TRIANGLES',
           'G2_TWO_TRIANGLES_1', 'G2_345_UNBOUNDED_1', 'G2_345_BOUNDED_1', 'G2_HOUSE_1', 'G2_CONTRACTIBLE_FACE',
           'G3_SIMPLEX', 'G3_CUBE_BOUNDED']

# Cell

# Isolated dart in 0-D
#   0
G0_ISOLATED_VERTEX = """\
    0
"""

### Two isolated darts (vertices) see BOOK Fig 4.4 on page 92
#   0 1
G0_TWO_ISOLATED_VERTICES = """\
    0 1
"""

### A pair or vertices (0-sphere) see BOOK Fig 4.4 on page 92
#   0 1
G0_TWO_IDENTIFIED_VERTICES = """\
    1 0
"""

# Cell

## 1-gMaps

#   0
G1_ISOLATED_DART = """\
    0
    0
"""

# Four 1-gMaps consisting of 2 darts follow

#   0 1
G1_0101 = """\
    0 1
    0 1
"""

#   0 1
G1_0110 = """\
    0 1
    1 0
"""

#   0 1
G1_1001 = """\
    1 0
    0 1
"""

# 1D loop, zero-based indices
#   0 1
G1_1010 = """\
    1 0
    1 0
"""

# 1D loop, one-based indices, see BOOK figure 3.19 on page 71
#   1 2
G1_LOOP_1 = """\
    2 1
    2 1
"""

# Cell
## 2-gMaps

### Bounded square
#   0 1 2 3 4 5 6 7
G2_SQUARE_BOUNDED = """\
    1 0 3 2 5 4 7 6
    7 2 1 4 3 6 5 0
    0 1 2 3 4 5 6 7
"""

### Bounded square, see BOOK Fig 4.48a
#   1 2 3 4 5 6 7 8
G2_SQUARE_BOUNDED_1 = """\
    2 1 4 3 6 5 8 7
    8 3 2 5 4 7 6 1
    1 2 3 4 5 6 7 8
"""

### Unbounded square
#   0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 16
G2_SQUARE_UNBOUNDED = """\
    1  0  3  2  5  4  7  6  9  8 11 10 13 12 15 14
    7  2  1  4  3  6  5  0 15 10  9 12 11 14 13  8
    8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7
"""

# Annulus, see BOOK Fig 4.48b
#   1 2 3 4 5 6 7 8
G2_ANNULUS_1 = """\
    2 1 4 3 6 5 8 7
    8 3 2 5 4 7 6 1
    1 2 8 7 5 6 4 3
"""

# Moebius see BOOK Fig 4.48c
#   1 2 3 4 5 6 7 8
G2_MOEBIUS_1 = """\
    2 1 4 3 6 5 8 7
    8 3 2 5 4 7 6 1
    1 2 7 8 5 6 3 4
"""

# Torus, see BOOK Fig 3.24 on page 76
#   1 2 3 4 5 6 7 8
G2_TORUS_1 = """\
    2 1 4 3 6 5 8 7
    8 3 2 5 4 7 6 1
    6 5 8 7 2 1 4 3
"""

# Two disconnected triangles, unbounded, zero-based indexing
#   0 1 2 3 4 5    6  7  8  9 10  11
G2_TWO_TRIANGLES = """\
    1 0 3 2 5 4    7  6  9  8 11  10
    5 2 1 4 3 0   11  8  7 10  9   6
    0 1 2 3 4 5    6  7  8  9 10  11
"""

# Two disconnected triangles, unbounded, one-based darts, see BOOK Fig 4.7
#   1 2 3 4 5 6    7  8  9 10  11 12
G2_TWO_TRIANGLES_1 = """\
    2 1 4 3 6 5    8  7 10  9 12  11
    6 3 2 5 4 1   12  9  8 11 10   7
    1 2 3 4 5 6    7  8  9 10 11  12
"""

###  triangle + quad + pentagon, unbounded. See BOOK Fig 3.21 page 73
#    1  2  3  4  5  6  7  8     9 10 11 12 13 14 15 16 17 18    19 20 21 22 23 24   25 26 27 28 29 30 31 32 33 34 35 36
G2_345_UNBOUNDED_1 = """\
     2  1  4  3  6  5  8  7    10  9 12 11 14 13 16 15 18 17    20 19 22 21 24 23   26 25 28 27 30 29 32 31 34 33 36 35
     8  3  2  5  4  7  6  1    18 11 10 13 12 15 14 17 16  9    24 21 20 23 22 19   36 27 26 29 28 31 30 33 32 35 34 25
    19 20 10  9 33 34 35 36     4  3 21 22 27 28 29 30 31 32     1  2 11 12 26 25   24 23 13 14 15 16 17 18  5  6  7  8
"""

###  triangle + quad + pentagon, bounded. See BOOK Fig 3.30 page 80
#    1  2  3  4  5  6  7  8     9 10 11 12 13 14 15 16 17 18    19 20 21 22 23 24
G2_345_BOUNDED_1 = """\
     2  1  4  3  6  5  8  7    10  9 12 11 14 13 16 15 18 17    20 19 22 21 24 23
     8  3  2  5  4  7  6  1    18 11 10 13 12 15 14 17 16  9    24 21 20 23 22 19
    19 20 10  9  5  6  7  8     4  3 21 22 13 14 15 16 17 18     1  2 11 12 23 24
"""

### HOUSE (triangle + quad) see PAPER Fig 5
#    1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
G2_HOUSE_1 = """\
     2  1  4  3  6  5  8  7 10  9 12 11 14 13 16 15 18 17 20 19 22 21 24 23
     8  3  2  5  4  7  6  1 14 11 10 13 12  9 24 17 16 19 18 21 20 23 22 15
    15 16  9 10 21 22 23 24  3  4 20 19 18 17  1  2 14 13 12 11  5  6  7  8
"""

### 3-adjacent faces, the middle one is contractible. See BOOK Figure 6.28 a
#   1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
G2_CONTRACTIBLE_FACE = """\
    2  1  4  3  6  5  8  7 10  9 12 11 14 13 16 15 18 17 20 19
    4  3  2  1 12  7  6  9  8 11 10  5 20 15 14 17 16 19 18 13
    6  5 13 14  2  1  7  8  9 10 11 12  3  4 15 16 17 18 19 20
"""

# Cell

###  3D simplex, bounded
#    0  1  2  3  4  5     6  7  8  9 10 11     12 13 14 15 16 17     18 19 20 21 22 23
G3_SIMPLEX = """\
     1  0  3  2  5  4     7  6  9  8 11 10     13 12 15 14 17 16     19 18 21 20 23 22
     5  2  1  4  3  0    11  8  7 10  9  6     17 14 13 16 15 12     23 20 19 22 21 18
     7  6 13 12 19 18     1  0 23 22 15 14      3  2 11 10 21 20      5  4 17 16  9  8
     0  1  2  3  4  5     6  7  8  9 10 11     12 13 14 15 16 17     18 19 20 21 22 23
"""

#    0  1  2  3  4  5  6  7     8  9 10 11 12 13 14 15    16 17 18 19 20 21 22 23   24 25 26 27 28 29 30 31   32 33 34 35 36 37 38 39   40 41 42 43 44 45 46 47
G3_CUBE_BOUNDED = """\
     1  0  3  2  5  4  7  6     9  8 11 10 13 12 15 14    17 16 19 18 21 20 23 22   25 24 27 26 29 28 31 30   33 32 35 34 37 36 39 38   41 40 43 42 45 44 47 46
     7  2  1  4  3  6  5  0    15 10  9 12 11 14 13  8    23 18 17 20 19 22 21 16   31 26 25 28 27 30 29 24   39 34 33 36 35 38 37 32   47 42 41 44 43 46 45 40
    41 40 15 14 33 32 27 26    47 46 23 22 35 34  3  2    45 44 31 30 37 36 11 10   43 42  7  6 39 38 19 18    5  4 13 12 21 20 29 28    1  0 25 24 17 16  9  8
     0  1  2  3  4  5  6  7     8  9 10 11 12 13 14 15    16 17 18 19 20 21 22 23   24 25 26 27 28 29 30 31   32 33 34 35 36 37 38 39   40 41 42 43 44 45 46 47
"""