# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/03_zoo_labels.ipynb (unless otherwise specified).

__all__ = ['str2labels', 'L2_CORNER', 'L2_TUNNEL', 'L2_TUNNEL_GRASS', 'L2_HOUSE', 'L2_NEST',
           'L2_TRAFFIC_LIGHTS_HOR_COMPACT', 'L2_TRAFFIC_LIGHTS', 'L2_TRAFFIC_LIGHTS_HOR', 'L2_TRAFFIC_LIGHTS_HOR_RGY',
           'L2_F5', 'L2_F5_FLIPPED', 'L2_F5_ROTATED', 'L2_F5_ROTATED_FLIPPED', 'L2_HORSE_SHOE', 'L2_SQUARES',
           'L2_SPIRAL', 'L2_SPIRAL_BWB', 'L2_SPIRAL_BWBW', 'L2_SPIRAL_WW', 'L2_SPIRAL_WB', 'L2_SPIRAL_BB',
           'L2_SPIRAL_BW']

# Cell

import numpy as np

# Cell


def str2labels (s):
    """Label image from a multiline string.

    Converts a multiline string to a height x width x 3 label image.
    The string may consists of digits 0-9 and one of: . k r g b c m y o w
    See below for examples.
    Args:
        s: a multiline string to be converted to labels.

    Returns:
        numpy array of shape height x width x 3
    """

    colors = {
        '0' :  [  0,   0,   0],    '.' : [  0,   0,   0],
        '1' :  [ 28,  28,  28],    'k' : [  0,   0,   0],
        '2' :  [ 56,  56,  56],    'r' : [255,   0,   0],
        '3' :  [ 85,  85,  85],    'g' : [  0, 255,   0],
        '4' :  [113, 113, 113],    'b' : [  0,   0, 255],
        '5' :  [141, 141, 141],    'c' : [  0, 255, 255],
        '6' :  [170, 170, 170],    'm' : [255,   0, 255],
        '7' :  [198, 198, 198],    'y' : [255, 255,   0],
        '8' :  [226, 226, 226],    'o' : [241,  68,  18],
        '9' :  [255, 255, 255],    'w' : [255, 255, 255],
    }

    n_lines = len(s.splitlines())

    labels = np.array ([colors [c] for c in s.split()]).reshape ((n_lines, -1, 3))
    return labels

# Cell


L2_CORNER = """\
. . .
w . .
"""

L2_TUNNEL = """\
. . .
. w .
"""

L2_TUNNEL_GRASS = """\
. . .
. w .
g g g
"""


L2_HOUSE = """\
. . . . .
. b . r .
. . . r .
g g g g g
"""

L2_NEST = """\
. . . .  .  . . . .
. y y y  c  g g g .
. y r y  .  g m g .
. y y y  c  g g g .
. . . .  .  . . . .
"""

L2_TRAFFIC_LIGHTS_HOR_COMPACT = """\
. . . . .
. r y g .
. . . . .
"""

L2_TRAFFIC_LIGHTS = """\
. . .
. r .
. . .
. y .
. . .
. g .
. . .
"""

L2_TRAFFIC_LIGHTS_HOR = """\
. . . . . . .
. r . y . g .
. . . . . . .
"""

L2_TRAFFIC_LIGHTS_HOR_RGY = """\
. . . . . . .
. r . g . y .
. . . . . . .
"""

# Cell

# 5-faces from Figure 1 from the following publication.
# Carine Grasset-Simon, Guillaume Damiand, Pascal Lienhardt.
# nD generalized map pyramids: defi- nition, representations and basic operations.
# Pattern Recognition, Elsevier, 2006, 39 (4), pp.527-538.

L2_F5 = """\
4 2 2 2
2 2 3 2
2 2 2 2
2 1 1 2
0 1 1 0
0 0 0 0
"""

L2_F5_FLIPPED = """\
0 0 0 0
0 1 1 0
2 1 1 2
2 2 2 2
2 2 3 2
4 2 2 2
"""

L2_F5_ROTATED = """\
0 0 2 2 2 4
0 1 1 2 2 2
0 1 1 2 3 2
0 0 2 2 2 2
"""

L2_F5_ROTATED_FLIPPED = """\
4 2 2 2 0 0
2 2 2 1 1 0
2 3 2 1 1 0
2 2 2 2 0 0
"""

# Cell

# Spirals and co from Walter G. Kropatsch, Yll Haxhimusa: Pyramid Benchmark Pictures.


L2_HORSE_SHOE = """\
. . . . . . . . . . . . . . . .
g r r r r r r r r r r r r r g .
g r b b b b b b b b b b b b g .
g r b . . . . . . . . . . b g .
g r b g r r r r r r r g . b g .
g r b g r b b b b b b g . b g .
g r b g r b . . . . b g . b g .
g r b g r b g r g . b g . b g .
g r b g r b g g g . b g . b g .
g r b g r b . . . . b g . b g .
g r b g r r r r r r r g . b g .
g r b g g g g g g g g g . b g .
g r b . . . . . . . . . . b g .
g r r r r r r r r r r r r r g .
g g g g g g g g g g g g g g g .
. . . . . . . . . . . . . . . .
"""

L2_SQUARES = """\
. . . . . . . . . . . . . . . .
. w w w w w w w w w w w w w w .
. w . . . . . . . . . . . . w .
. w . w w w w w w w w w w . w .
. w . w . . . . . . . . w . w .
. w . w . w w w w w w . w . w .
. w . w . w . . . . w . w . w .
. w . w . w . w w . w . w . w .
. w . w . w . w w . w . w . w .
. w . w . w . . . . w . w . w .
. w . w . w w w w w w . w . w .
. w . w . . . . . . . . w . w .
. w . w w w w w w w w w w . w .
. w . . . . . . . . . . . . w .
. w w w w w w w w w w w w w w .
. . . . . . . . . . . . . . . .
"""


L2_SPIRAL = """\
. . . . . . . . . . .
w w w w w w w w w w .
w . . . . . . . . w .
w . w w w w w w . w .
w . w . . . . w . w .
w . w . w w . w . w .
w . w . w . . w . w .
w . w . w w w w . w .
w . w . . . . . . w .
w . w w w w w w w w .
w . . . . . . . . . .
"""

# 3 spirals
L2_SPIRAL_BWB = """\
. w . . . . . . . . .
. w . w w w w w w w .
. w . w . . . . . w .
. w . w . w w w . w .
. w . w . w . w . w .
. w . w w w . w . w .
. w . . . . . w . w .
. w w w w w w w . w .
. . . . . . . . . w .
"""

# 4 spirals
L2_SPIRAL_BWBW = """\
. w . . . . . . . .
. w . w w w w w w .
. w . w . . . . w .
. w . w . w w . w .
. w . w w . w . w .
. w . . . . w . w .
. w w w w w w . w .
. . . . . . . . w .
"""

L2_SPIRAL_WW = """\
. . . . . . . . . w w w w w w w w w w w w w
. w w w w w w w . w . . . . . . . . . . . w
. w . . . . . w . w . w w w w w w w w w . w
. w . w w w . w . w . w . . . . . . . w . w
. w . w . w . w . w . w . w w w w w . w . w
. w . w . w w w . w . w . w . . . w . w . w
. w . w . . . . . w . w . w . w w w . w . w
. w . w w w w w w w . w . w . w . . . w . w
. w . . . . . . . . . w . w . w w w w w . w
. w w w w w w w w w w w . w . . . . . . . w
. . . . . . . . . . . . . w w w w w w w w w
"""

L2_SPIRAL_WB = """\
. . . . . . . . . w w w w w w w w w w w w w
. w w w w w w w . w . . . . . . . . . . . w
. w . . . . . w . w . w w w w w w w w w . w
. w . w w w . w . w . w . . . . . . . w . w
. w . w . w . w . w . w . w w w w w . w . w
. w . w . w w w . w . w . w . . . w . w . w
. w . w . . . . . w . w . w . w . w . w . w
. w . w w w w w w w . w . w . w . . . w . w
. w . . . . . . . . . w . w . w w w w w . w
. w w w w w w w w w w w . w . . . . . . . w
. . . . . . . . . . . . . w w w w w w w w w
"""

L2_SPIRAL_BB = """\
. . . . . . . . . w w w w w w w w w w w w w
. w w w w w w w . w . . . . . . . . . . . w
. w . . . . . w . w . w w w w w w w w w . w
. w . w w w . w . w . w . . . . . . . w . w
. w . w . . . w . w . w . w w w w w . w . w
. w . w . w w w . w . w . w . . . w . w . w
. w . w . . . . . w . w . w . w . w . w . w
. w . w w w w w w w . w . w . w . . . w . w
. w . . . . . . . . . w . w . w w w w w . w
. w w w w w w w w w w w . w . . . . . . . w
. . . . . . . . . . . . . w w w w w w w w w
"""

L2_SPIRAL_BW = """\
. . . . . . . . . w w w w w w w w w w w w w
. w w w w w w w . w . . . . . . . . . . . w
. w . . . . . w . w . w w w w w w w w w . w
. w . w w w . w . w . w . . . . . . . w . w
. w . w . . . w . w . w . w w w w w . w . w
. w . w . w w w . w . w . w . . . w . w . w
. w . w . . . . . w . w . w . w w w . w . w
. w . w w w w w w w . w . w . w . . . w . w
. w . . . . . . . . . w . w . w w w w w . w
. w w w w w w w w w w w . w . . . . . . . w
. . . . . . . . . . . . . w w w w w w w w w
"""